# Generated by Django 4.0.5 on 2022-06-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('is_completed', models.BooleanField(default=False, verbose_name='выполнено')),
            ],
        ),
    ]
